package controller;

public enum Actions {
	LETS_DO_IT, SIGN_IN, USER, BUSINESS_OWNER, PRODUCT_ADD_MY_CAR, JOIN, LOGIN, SIGN_UP, JOIN_ACCOUNT_OWNER, RESTAURANT, CREATE_PRODUCT, GENERATE_ORDER, CREATE_PRODUCT_NEW,  
	BACK_VIEW_THREE;
}