package controller;

public enum Actions {
	LETS_DO_IT, SIGN_IN, USER, BUSINESS_OWNER, PRODUCT_ADD_MY_CAR, JOIN, LOGIN, SIGN_UP, JOIN_ACCOUNT_OWNER, RESTAURANT, CREATE_PRODUCT, GENERATE_ORDER, CREATE_PRODUCT_NEW,  
	BACK_VIEW_THREE, BACK_OF_OPTIONS_DIALOG, EDIT_PRODUCT_BYOWNER, SAVE_EDITED_PRODUCT, SHOW_DIALOG_OPTIONS, SEARCH_PRODUCT_BYWORD, SEARCH_OWNER_BYWORD, SHOW_MENU_FOR_OWNER, SHOW_ORDERS_FOR_OWNER, CHANGE_STATUS,
	BACK_SIX, EXIT, CANCEL_ORDER, GENERATE_SHOPPING_CAR;
}